---
driver:
  name: digitalocean
  # Clamd will fail to start on some distros with only 512MB
  size: 1gb
  region: ams3
platforms:
  - name: ubuntu-14-04-x64
  - name: centos-7-0-x64
  - name: centos-6-5-x64
suites:
- name: default
  run_list:
  - recipe[milter-test]
