[local_phases]
unit = "chef exec rspec spec/"
lint = "chef exec cookstyle --display-cop-names --extra-details"
syntax = "chef exec foodcritic . --exclude spec -f any"
provision = "echo skipping"
deploy = "echo skipping"
smoke = "echo skipping"
functional = "echo skipping"
cleanup = "echo skipping"
